<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

    <ItemGroup>

    <Reference Include="BepInEx.Core">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\lib\BepInEx.Core.dll</HintPath>
    </Reference>

    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\lib\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>

    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\lib\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>

    <Reference Include="Il2Cppmscorlib">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libIl2Cppmscorlib.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libAssembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libUnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="Unity.InputSystem">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libUnity.InputSystem.dll</HintPath>
    </Reference>

    <Reference Include="Unity.TextMeshPro">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libUnity.TextMeshPro.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.UI">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libUnityEngine.UI.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.AudioModule">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libUnityEngine.AudioModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libUnityEngine.DirectorModule.dll</HintPath>
    </Reference>

    <Reference Include="Deadshot.Data">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libDeadshot.Data.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libUnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>

    <Reference Include="Il2CppSystem">
      <HintPath>C:\Code\DeadshotMods\DeadshotModAPI\libIl2CppSystem.dll</HintPath>
    </Reference>

  </ItemGroup>

</Project>
